FROM resin/rpi-raspbian:stretch
LABEL maintainer="jay101630@gmail.com"

COPY ./qemu-arm-static /usr/bin/qemu-arm-static

RUN apt-get update

RUN apt-get install \
    build-essential \
    cmake \
    git \
    wget \
    unzip \
    libgtk2.0-dev \
    pkg-config \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-dev \
    libblas-dev \
    liblapack-dev \
    libhdf5-dev \
    python3-h5py \
    python3-scipy  \
    python3-pil

# instal numpy and keras
RUN pip3 install numpy keras

# install OpenCV 3.4.0
WORKDIR /
RUN wget https://github.com/opencv/opencv/archive/3.4.0.zip && unzip 3.4.0.zip
RUN mkdir /opencv-3.4.0/build \
&& cd /opencv-3.4.0/build \
&& cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .. \
&& make -j4 \
&& make install \
&& rm -rf /opencv-3.4.0 \
&& rm 3.4.0.zip

# install tensorflow
RUN pip3 install tensorflow
RUN pip3 install Pillow


# yad2k
COPY ./src/ /app
WORKDIR /app/
#RUN ./yad2k.py model_data/yolov1-tiny.cfg model_data/yolo-tiny.weights model_data/yolo-tiny.h5



